export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_BOUNTY_VISABILITY = "SET_BOUNTY_VISABILITY";
export const visabilityFilters = {
    SHOW_ALL : "SHOW_ALL",
    SHOW_COMPLETED : "SHOW_COMPLETED",
    SHOW_ACTIVE : "SHOW_ACTIVE"
};
export const TOGGLE_BOUNTY = "TOGGLE_BOUNTY";
export const CREATE_BOUNTY = "CREAtE_BOUNTY";
